<template>
  <el-loading
    :loading="isOptimizing"
    text="正在优化标题，请稍候..."
    fullscreen
  ></el-loading>
  <div class="titlePage">
    <div class="title-generator">
      <el-card class="mt-4" :disabled="!selectedProject">
        <el-divider>选择项目</el-divider>
        <el-row>
          <el-col :span="12" style="margin: 0 auto">
            <el-form label-width="100px">
              <el-form-item label="选择项目">
                <el-select
                  v-model="selectedProject"
                  @change="handleProjectChange"
                  placeholder="请选择项目"
                >
                  <el-option
                    v-for="project in projectList"
                    :key="project.folderName"
                    :label="project.folderName"
                    :value="project.folderName"
                  />
                </el-select>
              </el-form-item>
            </el-form>
          </el-col>
        </el-row>
        <div
          class="header"
          style="
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 10px;
          "
        >
          <div>📦 关键词词库列表</div>
          <div style="display: flex; gap: 10px; align-items: center">
            <el-button
              type="success"
              :disabled="!selectedProject"
              @click="autoGenerateDialogVisible = true"
              >AI 生成词库</el-button
            >
            <el-button
              type="primary"
              :disabled="!selectedProject"
              @click="openAddDialog"
              >新增词库</el-button
            >
            <el-button
              type="danger"
              :disabled="!selectedProject || !selectedLibRows.length"
              @click="batchDeleteLibraries"
              >批量删除</el-button
            >
            <el-button :disabled="!selectedProject" @click="exportLibraries"
              >导出词库</el-button
            >
            <el-upload
              :disabled="!selectedProject"
              :show-file-list="false"
              accept=".json"
              :auto-upload="false"
              @change="importLibraries"
            >
              <el-button>导入词库</el-button>
            </el-upload>
          </div>
        </div>

        <el-table
          :data="wordLibraries"
          border
          @selection-change="(val: any) => (selectedLibRows = val)"
        >
          <el-table-column type="selection" width="40" />
          <el-table-column prop="name" label="词库名称" width="200" />
          <el-table-column label="中文关键词">
            <template #default="{ row }">
              <div v-if="row.words">
                <el-tag
                  v-for="(w, i) in row.words"
                  :key="i"
                  type="primary"
                  class="mb-1 mr-1"
                >
                  {{ w.zh }}
                </el-tag>
              </div>
            </template>
          </el-table-column>

          <el-table-column label="英文关键词">
            <template #default="{ row }">
              <div v-if="row.words">
                <el-tag
                  v-for="(w, i) in row.words"
                  :key="i"
                  type="success"
                  class="mb-1 mr-1"
                >
                  {{ w.en }}
                  <el-icon><CloseBold /></el-icon>
                </el-tag>
              </div>
            </template>
          </el-table-column>
          <el-table-column label="操作" width="160">
            <template #default="{ row, $index }">
              <el-button size="small" @click="editLibrary(row)">编辑</el-button>
              <el-button
                size="small"
                type="danger"
                @click="removeLibrary($index)"
                >删除</el-button
              >
            </template>
          </el-table-column>
        </el-table>
      </el-card>

      <el-card class="mt-4" :disabled="!selectedProject">
        <template #header>
          <div class="flex justify-between items-center">
            <div class="flex items-center gap-2 font-bold text-base">
              <span style="font-weight: bold">🔀 组合顺序 + 关键词字段</span>
            </div>
            <div class="flex items-center gap-2" style="margin-top: 10px">
              <div class="method" style="display: flex; margin-top: 10px">
                <span>目标标题数：</span>
                <el-input-number
                  v-model="generateCount"
                  :min="1"
                  size="small"
                />
                <div class="connect" style="margin-left: auto">
                  <span style="font-size: 14px; margin-right: 10px"
                    >关键词连接符:
                  </span>
                  <el-select
                    v-model="keywordJoiner"
                    placeholder="选择连接符"
                    size="small"
                    style="width: 200px; margin-right: 10px"
                  >
                    <el-option label="空格" value=" " />
                    <el-option label="横杠 -" value="-" />
                    <el-option label="逗号 ," value=", " />
                    <el-option label="无连接" value="" />
                  </el-select>
                  <el-button
                    type="primary"
                    size="small"
                    @click="titleCombineConfig.push({ libId: -1, field: 'en' })"
                  >
                    <el-icon size="16">
                      <Plus />
                    </el-icon>
                    添加组合项
                  </el-button>
                  <el-button
                    type="success"
                    icon=""
                    size="small"
                    @click="generateTitles"
                  >
                    <el-icon size="16">
                      <MagicStick />
                    </el-icon>
                    生成标题
                  </el-button>
                </div>
              </div>
            </div>
          </div>
        </template>

        <div
          v-for="(item, index) in titleCombineConfig"
          :key="index"
          class="config-row"
        >
          <el-row :gutter="10" justify="center" align="middle">
            <el-col :span="6">
              <el-select
                v-model="item.libId"
                placeholder="选择词库"
                size="small"
                style="width: 100%"
              >
                <el-option
                  v-for="lib in wordLibraries"
                  :key="lib.id"
                  :label="lib.name"
                  :value="lib.id"
                />
              </el-select>
            </el-col>

            <el-col :span="4">
              <el-select
                v-model="item.field"
                placeholder="关键词字段"
                size="small"
                style="width: 100%"
              >
                <el-option label="中文" value="zh" />
                <el-option label="英文" value="en" />
              </el-select>
            </el-col>

            <el-col :span="2">
              <el-button
                type="danger"
                icon
                size="small"
                circle
                @click="titleCombineConfig.splice(index, 1)"
              >
                <el-icon><Delete /></el-icon>
              </el-button>
            </el-col>
          </el-row>
        </div>
      </el-card>

      <el-card class="mt-4">
        <template #header>
          <el-row>
            <el-col :span="5">
              <div class="title">
                📦 当前项目标题（共 {{ productTitles.length }} 条）
              </div>
            </el-col>
            <el-col :span="9">
              <div class="applyRule">
                <el-input-number
                  v-model="pageSize"
                  :min="1"
                  :max="100"
                ></el-input-number>
                <el-radio-group v-model="applyRule">
                  <!-- 应用规则 -->
                  <el-tooltip
                    class="box-item"
                    effect="dark"
                    content="类目按照顺序分配标题,如: 10个类目1个类目1个标题,循环分配"
                    placement="top"
                  >
                    <el-radio value="轮循模式">轮循模式</el-radio>
                  </el-tooltip>
                  <el-tooltip
                    class="box-item"
                    effect="dark"
                    content="标题数÷类目数均分标题,如: 10个类目100个标题,1个类目10个标题"
                    placement="top"
                  >
                    <el-radio value="均分模式">均分模式</el-radio>
                  </el-tooltip>
                </el-radio-group>
                <el-tooltip
                  class="box-item"
                  effect="dark"
                  content="每个类目分配多少个标题"
                  placement="right"
                >
                  <el-button
                    type="primary"
                    @click="applyToCategory($event, pageSize)"
                    style="margin-left: 10px"
                    >应用</el-button
                  >
                </el-tooltip>
              </div>
            </el-col>
          </el-row>
          <el-row
            style="
              padding-top: 10px;
              margin-top: 10px;
              border-top: 1px solid #eee;
            "
          >
            <el-col
              :span="24"
              style="
                display: flex;
                justify-content: space-between;
                align-items: center;
              "
            >
              <div
                class="select text-left mb-2"
                style="display: flex; align-items: center"
              >
                <el-button
                  size="small"
                  type="primary"
                  plain
                  @click="selectAllCurrentPageTitles"
                  :disabled="!productTitles.length"
                >
                  全选当前页
                </el-button>
                <el-button
                  size="small"
                  type="success"
                  plain
                  @click="selectAllTitles()"
                  :disabled="!productTitles.length"
                >
                  全选全部
                </el-button>
              </div>
              <div>
                <el-button size="small" @click="batchSetCategory"
                  >批量编辑分类</el-button
                >
                <el-button size="small" type="danger" @click="batchDeleteTitles"
                  >批量删除</el-button
                >
                <!-- <el-button
                size="small"
                type="primary"
                @click="openOptimizeDialog"
                :disabled="!selectedRows.length"
              >
                批量优化标题
              </el-button> -->
                <el-button size="small" type="success" @click="exportTitleData"
                  >导出标题</el-button
                >
              </div>
            </el-col>
          </el-row>
        </template>

        <el-table
          :data="productPagedTitles"
          border
          @selection-change="handleSelectionChange"
          :row-key="(row: any) => row.title"
          ref="titleTableRef"
        >
          ref="titleTableRef" >
          <el-table-column type="selection" width="50" />
          <el-table-column prop="id" label="id" width="50">
            <template #default="{ row }"> {{ row.id + 1 }} </template>
          </el-table-column>
          <el-table-column prop="category" label="类目名称" width="180">
            <template #default="{ row }">
              <el-select
                v-model="row.category.id"
                placeholder="选择类目"
                size="small"
                @change="
                  (val) => {
                    const selectedCat = categoryOptions.find(
                      (c) => c.id === val
                    );
                    row.category.name = selectedCat ? selectedCat.name : '';
                  }
                "
              >
                <el-option
                  v-for="cat in categoryOptions"
                  :key="cat.id"
                  :label="`${cat.name} (${cat.id})`"
                  :value="cat.id"
                />
              </el-select>
            </template>
          </el-table-column>
          <el-table-column label="标题预览" show-overflow-tooltip>
            <template #default="{ row }">
              <span>{{ row.title }}</span>
            </template>
          </el-table-column>
          <el-table-column label="操作" width="150">
            <template #default="{ row, $index }">
              <el-button size="small" type="primary" @click="editTitle(row)"
                >编辑</el-button
              >
              <el-button
                size="small"
                type="danger"
                @click="productTitles.splice($index, 1)"
                >删除</el-button
              >
            </template>
          </el-table-column>
        </el-table>

        <div
          class="table-footer text-right mt-3"
          style="display: flex; margin-top: 15px"
        >
          <el-pagination
            v-model:current-page="currentPage"
            :page-size="pageSize"
            layout="prev, pager, next, total"
            :total="productTitles.length"
          />
        </div>
      </el-card>
    </div>
  </div>
  <el-dialog
    v-model="batchCategoryDialogVisible"
    title="批量设置分类"
    width="400px"
    align-center
  >
    <el-form label-width="80px">
      <el-form-item label="选择类目">
        <el-select
          v-model="batchSelectedCategory"
          placeholder="请选择类目"
          style="width: 100%"
        >
          <!-- 修改选项显示方式 -->
          <el-option
            v-for="cat in categoryOptions"
            :key="cat.id"
            :label="`${cat.name} (${cat.id})`"
            :value="cat"
          />
        </el-select>
      </el-form-item>
    </el-form>

    <template #footer>
      <el-button @click="batchCategoryDialogVisible = false">取消</el-button>
      <el-button type="primary" @click="confirmBatchCategory">确认</el-button>
    </template>
  </el-dialog>
  <!-- 📥 新增/编辑词库弹窗 -->
  <el-dialog
    v-model="dialogVisible"
    :title="dialogMode === 'edit' ? '编辑词库' : '新增词库'"
    width="800px"
  >
    <el-row style="margin-bottom: 10px">
      <el-col :span="8">
        <el-form-item label="词库名称" style="margin-bottom: 0">
          <el-input
            size="small"
            v-model="newLibrary.name"
            placeholder="例如：卖点、品类、使用场景"
          />
        </el-form-item>
      </el-col>
      <el-col
        :span="3"
        style="display: flex; align-items: center; margin-left: auto"
      >
        <el-button
          size="small"
          type="primary"
          @click="addKeywordRow"
          style="margin-left: 10px"
          >新增关键词</el-button
        >
      </el-col>
    </el-row>
    <el-table :data="(newLibrary as any).words" border height="200">
      <el-table-column prop="zh" label="中文关键词" align="center">
        <template #default="{ row }">
          <el-input v-model="row.zh" placeholder="中文" />
        </template>
      </el-table-column>
      <el-table-column prop="en" label="英文关键词" align="center">
        <template #default="{ row }">
          <el-input v-model="row.en" placeholder="English" />
        </template>
      </el-table-column>
      <el-table-column label="操作" width="200" align="center">
        <template #default="scope">
          <el-button
            type="primary"
            size="small"
            @click="newLibrary.words.splice(scope.$index, 1)"
          >
            <el-icon><Edit /></el-icon
          ></el-button>
          <el-button
            type="danger"
            size="small"
            @click="newLibrary.words.splice(scope.$index, 1)"
          >
            <el-icon><Delete /></el-icon
          ></el-button>
        </template>
      </el-table-column>
    </el-table>

    <template #footer>
      <el-button @click="dialogVisible = false">取消</el-button>
      <el-button type="primary" @click="confirmLibrary">确定</el-button>
    </template>
  </el-dialog>
  <el-dialog
    v-model="autoGenerateDialogVisible"
    title="AI 生成词库"
    width="500px"
  >
    <el-form label-width="100px">
      <el-form-item label="AI模型">
        <el-select
          v-model="selectedAiType"
          placeholder="请选择AI模型"
          style="width: 100%"
        >
          <el-option label="通义千问(免费)" :value="'Qwen'" />
          <!-- <el-option label="openAI(收费接口，服务不稳定)" value="openai" /> -->
        </el-select>
      </el-form-item>
      <el-form-item label="产品名称">
        <el-input v-model="productName" placeholder="请输入产品名称" />
      </el-form-item>
      <el-form-item label="产品图片">
        <el-upload
          :show-file-list="false"
          :auto-upload="false"
          accept="image/*"
          :before-upload="
            (file: any) => {
              selectedImageFile = file;
              return false;
            }
          "
        >
          <el-button>上传图片</el-button>
        </el-upload>
        <div
          v-if="selectedImageFile"
          style="margin-top: 8px; font-size: 12px; color: #999"
        >
          当前已选：{{ selectedImageFile.name }}
        </div>
      </el-form-item>
      <el-form-item label="补充说明">
        <el-input
          type="textarea"
          v-model="productSupplement"
          placeholder="（可选）提供额外说明、材料、用途等有助于提升生成质量"
          rows="3"
        />
      </el-form-item>
    </el-form>

    <template #footer>
      <el-button
        @click="
          () => {
            autoGenerateDialogVisible = false;
            aiWordLibLoading = false;
          }
        "
        >取消</el-button
      >
      <el-button
        type="primary"
        :loading="aiWordLibLoading"
        @click="autoGenerateLibraries"
        >立即生成</el-button
      >
    </template>
  </el-dialog>
  <el-dialog v-model="optimizeDialogVisible" title="批量优化标题" width="500px">
    <el-form label-width="100px">
      <el-form-item label="排除优化词库">
        <el-select
          v-model="excludedLibraries"
          multiple
          placeholder="请选择要排除的词库"
          style="width: 100%"
        >
          <el-option
            v-for="lib in wordLibraries"
            :key="lib.id"
            :label="lib.name"
            :value="lib.id"
          />
        </el-select>
      </el-form-item>
      <el-form-item label="追加位置">
        <el-radio-group v-model="appendPosition">
          <el-radio label="before">标题前</el-radio>
          <el-radio label="after">标题尾部</el-radio>
        </el-radio-group>
      </el-form-item>
    </el-form>
    <template #footer>
      <el-button @click="optimizeDialogVisible = false">取消</el-button>
      <el-button type="primary" @click="startBatchOptimize">开始优化</el-button>
    </template>
  </el-dialog>
</template>

<style lang="scss" scoped>
.titlePage {
  height: 100vh;
  overflow-y: auto;
  .title-generator {
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
    padding-bottom: 100px;
  }
  .mb-1 {
    margin-bottom: 5px;
  }
  .mr-1 {
    margin-right: 5px;
  }
  .mt-4 {
    margin-top: 20px;
  }
  .applyRule {
    display: flex;
    justify-content: space-around;
    align-items: center;
    width: 100%;
    font-size: 14px;
  }
  .config-row {
    padding: 10px 0;
    border-bottom: 1px dashed #e4e7ed;
    margin-bottom: 5px;
  }
  .table-footer {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    align-items: center;
    margin-top: 15px;
  }
}
</style>

<script setup lang="ts">
import { ref, reactive, computed, onMounted, h, nextTick, watch } from "vue";
import { ElMessage, ElMessageBox, ElNotification } from "element-plus";
import {
  Edit,
  Delete,
  Plus,
  MagicStick,
  Connection,
  // @ts-ignore 忽略类型检查,因为Vue单文件组件没有类型定义
} from "@element-plus/icons-vue";
import * as XLSX from "xlsx";

// 项目信息
const projectList = ref<any[]>([]);
const selectedProject = ref("");
const productTitles = ref<any[]>([]);
const selectedRows = ref<any[]>([]);
const currentPage = ref(1);
const pageSize = ref(10);

// 词库相关
const wordLibraries = ref<any[]>([]);
const idCounter = ref(0);
const titleCombineConfig = ref<{ libId: number; field: "zh" | "en" }[]>([]);
const generateCount = ref(20);
const generatedTitles = ref<string[]>([]);
const categoryOptions = ref<Array<{ id: string; name: string }>>([]);
const selectedAiType = ref("Qwen");
const aiWordLibLoading = ref(false);
const productSupplement = ref("");
const selectedLibRows = ref<any[]>([]);
const keywordJoiner = ref(" ");
// 应用规则
const applyRule = ref("轮循模式");
// 弹窗状态
const dialogVisible = ref(false);
const dialogMode = ref<"add" | "edit">("add");
const newLibrary = ref({
  id: -1,
  name: "",
  words: [
    {
      zh: "",
      en: "",
    },
  ],
});
const productName = ref("");
const selectedImageFile = ref<File | null>(null);
const autoGenerateDialogVisible = ref(false);
const batchCategoryDialogVisible = ref(false);
const batchSelectedCategory = ref<{ id: string; name: string } | null>(null);
// 批量优化相关状态
const optimizeDialogVisible = ref(false); // 优化弹窗是否可见
const excludedLibraries = ref<number[]>([]); // 排除的词库ID
const appendPosition = ref<"before" | "after">("after"); // 追加位置
const isOptimizing = ref(false); // 是否正在优化
const optimizationLoadingText = ref("正在优化标题，请稍候..."); // 加载提示文本

// 分页显示
const productPagedTitles = computed(() => {
  const start = (currentPage.value - 1) * pageSize.value;
  const end = start + pageSize.value;
  return productTitles.value.slice(start, end).map((t) => ({
    ...t,
    categoryDisplay: t.category ? `${t.category.name} (${t.category.id})` : "",
  }));
});
const selectedTitleSet = ref<Set<string>>(new Set());
const allSelectedRows = ref<any[]>([]);
const titleTableRef = ref(); // 获取表格实例

// 打开优化弹窗
function openOptimizeDialog() {
  optimizeDialogVisible.value = true;
}

// 开始批量优化
async function startBatchOptimize() {
  if (selectedRows.value.length === 0) {
    ElMessage.warning("请选择要优化的标题");
    return;
  }
  console.log(selectedRows.value);
  // 限制一次最多10个标题
  const titlesToOptimize = selectedRows.value.map((row) => row.title);
  const excludedWords = excludedLibraries.value
    .map((libId) => {
      const lib = wordLibraries.value.find((l) => l.id === libId);
      return lib?.words.map((w: { zh: any; en: any }) => w.zh || w.en) || [];
    })
    .flat();

  // 显示全屏加载状态
  isOptimizing.value = true;
  optimizationLoadingText.value = `正在优化标题，请稍候...`;

  try {
    // 循环请求每十个标题
    const chunkSize = 10;
    for (let i = 0; i < titlesToOptimize.length; i += chunkSize) {
      const chunk = titlesToOptimize.slice(i, i + chunkSize);
      const res = await fetch("http://localhost:3100/optimize-titles", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          titles: chunk,
          aiType: "Qwen",
        }),
      });

      const { success, data } = await res.json();
      if (!success) throw new Error("优化失败");

      // 更新表格数据
      data.forEach((optimizedTitle: string, index: number) => {
        const row = selectedRows.value[i + index];
        if (row) row.title = optimizedTitle;
      });

      // 提示用户当前进度
      ElMessage.success(
        `已优化 ${Math.min(chunk.length, titlesToOptimize.length - i)} 个标题`
      );
    }

    ElMessage.success("所有标题优化完成");
  } catch (err) {
    console.error("优化失败", err);
    ElMessage.error("优化失败，请稍后重试");
  } finally {
    // 隐藏加载状态并关闭弹窗
    isOptimizing.value = false;
    optimizeDialogVisible.value = false;
  }
}

// 标题分页相关
function applyToCategory(event: any, newSize: number) {
  console.log("每页显示数据量:", newSize);

  pageSize.value = newSize;
  currentPage.value = 1;

  const categories = categoryOptions.value;
  const titles = productTitles.value;

  const categoryCount = categories.length;
  const titlesCount = titles.length;

  console.log("类目数量:", categoryCount, "标题数量:", titlesCount);

  if (categoryCount === 0) {
    ElMessage.warning("请先选择类目");
    return;
  }

  // 清除所有已有分类
  titles.forEach((title) => {
    title.category = null;
  });

  if (applyRule.value === "轮循模式") {
    const maxDivisible =
      Math.floor(titlesCount / categoryCount) * categoryCount;
    const remainingCount = titlesCount - maxDivisible;

    // 轮循分配完整部分
    for (let i = 0; i < maxDivisible; i++) {
      const categoryIndex = i % categoryCount;
      titles[i].category = {
        id: categories[categoryIndex].id,
        name: categories[categoryIndex].name,
      };
    }

    // 处理剩余部分
    if (remainingCount > 0) {
      const remainingTitles = titles.slice(maxDivisible);
      showRemainingDialog(remainingTitles, "轮循模式");
    } else {
      ElMessage.success("所有标题已均匀分配完成");
    }
  } else if (applyRule.value === "均分模式") {
    const baseCount = Math.floor(titlesCount / categoryCount);
    const remainingCount = titlesCount - baseCount * categoryCount;

    let currentIndex = 0;

    // 均分基础部分
    for (let i = 0; i < categoryCount; i++) {
      for (let j = 0; j < baseCount; j++) {
        titles[currentIndex++].category = {
          id: categories[i].id,
          name: categories[i].name,
        };
      }
    }

    // 处理剩余部分
    if (remainingCount > 0) {
      const remainingTitles = titles.slice(currentIndex);
      showRemainingDialog(remainingTitles, "均分模式");
    } else {
      ElMessage.success("所有标题已均匀分配完成");
    }
  }

  console.log("所有标题已分类目", titles);
}
function showRemainingDialog(remainingTitles: any[], mode: string) {
  const remainingCount = remainingTitles.length;
  const message =
    mode === "轮循模式"
      ? `轮循模式下有${remainingCount}个标题无法均匀分配，请选择处理方式`
      : `均分模式下有${remainingCount}个标题无法均匀分配，请选择处理方式`;

  ElMessageBox.confirm(message, "处理剩余标题", {
    confirmButtonText:
      mode === "轮循模式" ? "继续轮循分配" : "轮循分配剩余标题",
    cancelButtonText: "手动指定类目",
    distinguishCancelAndClose: true,
    type: "warning",
  })
    .then(() => {
      // 继续自动轮循分配
      remainingTitles.forEach((title, index) => {
        title.category =
          categoryOptions.value[index % categoryOptions.value.length];
      });
      ElMessage.success("所有标题已分配完成");
    })
    .catch((action) => {
      if (action === "cancel") {
        selectedRows.value = remainingTitles;
        batchSetCategory(); // 打开批量编辑弹窗
      } else {
        ElMessage.info("已取消分配操作");
      }
    });
}
function handleSelectionChange(rows: any[]) {
  selectedRows.value = rows;
  const currentPageKeys = productPagedTitles.value.map((r) => r.title);
  currentPageKeys.forEach((key) => selectedTitleSet.value.delete(key)); // 清除当前页旧选中

  rows.forEach((r) => selectedTitleSet.value.add(r.title)); // 添加新选中
}

function restoreSelection() {
  if (!titleTableRef.value) return;
  nextTick(() => {
    productPagedTitles.value.forEach((row) => {
      if (selectedTitleSet.value.has(row.title)) {
        titleTableRef.value!.toggleRowSelection(row, true);
      }
    });
  });
}

watch([currentPage, productTitles], restoreSelection);

function selectAllCurrentPageTitles() {
  if (!titleTableRef.value) return;

  const table = titleTableRef.value;
  const isAllSelected = productPagedTitles.value.every((row: any) =>
    selectedTitleSet.value.has(row.title)
  );

  productPagedTitles.value.forEach((row: any) => {
    const key = row.title;
    if (isAllSelected) {
      selectedTitleSet.value.delete(key);
      table.toggleRowSelection(row, false);
    } else {
      selectedTitleSet.value.add(key);
      table.toggleRowSelection(row, true);
    }
  });
}

// 工具函数
function parseWords(raw: string): string[] {
  return raw
    .replace(/，/g, ",")
    .replace(/\s+/g, ",")
    .replace(/,+/g, ",")
    .split(",")
    .map((w) => w.trim())
    .filter(Boolean);
}

function normalizeRawWords(raw: string): string {
  return raw
    .replace(/，/g, ",")
    .replace(/\s+/g, ",")
    .replace(/,+/g, ",")
    .trim();
}
async function saveLibrariesToFile() {
  const project = projectList.value.find(
    (p) => p.folderName === selectedProject.value
  );
  if (!project) return;

  const content = JSON.stringify(wordLibraries.value, null, 2);
  const targetPath = `${project.folderPath}\\词库.json`;

  try {
    await window.electronAPI.saveFileSilently(content, targetPath);
  } catch (err) {
    console.error("词库保存失败：", err);
    ElMessage.error("词库文件保存失败");
  }
}
// 打开新增词库弹窗
function openAddDialog() {
  dialogMode.value = "add";
  newLibrary.value = {
    id: -1,
    name: "",
    words: [
      {
        zh: "",
        en: "",
      },
    ],
  };
  dialogVisible.value = true;
}
function addKeywordRow() {
  // 初始化 words 数组，如果不存在则创建空数组
  (newLibrary.value as any).words = (newLibrary.value as any).words || [];
  (newLibrary.value as any).words.push({ zh: "", en: "" });
}

function editLibrary(row: any) {
  dialogMode.value = "edit";
  newLibrary.value = {
    id: row.id,
    name: row.name,
    words: row.words,
  };
  console.log(newLibrary.value);

  dialogVisible.value = true;
}

// 确认保存词库
function confirmLibrary() {
  const words = newLibrary.value.words.filter(
    (w) => w.zh.trim() || w.en.trim()
  );

  if (!newLibrary.value.name || words.length === 0) {
    ElMessage.warning("词库名称不能为空，且至少填写一个中或英文关键词");
    return;
  }

  const payload = {
    id: dialogMode.value === "edit" ? newLibrary.value.id : idCounter.value++,
    name: newLibrary.value.name.trim(),
    words: words.map((w) => ({
      zh: w.zh.trim(),
      en: w.en.trim(),
    })),
  };

  if (dialogMode.value === "edit") {
    const index = wordLibraries.value.findIndex((l) => l.id === payload.id);
    if (index !== -1) wordLibraries.value[index] = payload;
  } else {
    wordLibraries.value.push(payload);
  }

  saveLibrariesToFile(); // 同步写入JSON文件
  dialogVisible.value = false;
  ElMessage.success("词库已保存");

  // 重置表单
  newLibrary.value = {
    id: -1,
    name: "",
    words: [{ zh: "", en: "" }],
  };
}

// 删除词库
function removeLibrary(index: number) {
  wordLibraries.value.splice(index, 1);
  saveLibrariesToFile();
}

function batchDeleteLibraries() {
  if (!selectedLibRows.value.length) {
    ElMessage.warning("请先选择词库");
    return;
  }
  ElMessageBox.confirm("确认删除选中的词库吗？", "批量删除", {
    type: "warning",
  }).then(() => {
    wordLibraries.value = wordLibraries.value.filter(
      (lib) => !selectedLibRows.value.includes(lib)
    );
    selectedLibRows.value = [];
    ElMessage.success("已删除所选词库");
  });
}

// 导出词库
function exportLibraries() {
  const project = projectList.value.find(
    (p) => p.folderName === selectedProject.value
  );
  if (!project) return;

  const content = JSON.stringify(wordLibraries.value, null, 2);
  const filename = "词库.json";
  const defaultPath = project.folderPath;

  window.electronAPI
    .saveFile(content, filename, defaultPath)
    .then(() => {
      ElMessage.success("词库已导出到项目目录");
    })
    .catch((err: any) => {
      console.error("导出失败:", err);
      ElMessage.error("词库导出失败");
    });
}

// 导入词库
function importLibraries(file: any) {
  const reader = new FileReader();
  reader.onload = () => {
    try {
      const result = JSON.parse(reader.result as string);
      if (Array.isArray(result)) {
        result.forEach((item) => {
          item.id = idCounter.value++;
          if (!item.words && item.wordsRaw) {
            // 兼容旧结构
            const words = parseWords(item.wordsRaw).map((w) => ({
              zh: w,
              en: w,
            }));
            item.words = words;
          }
        });
        wordLibraries.value.push(...result);
        ElMessage.success("词库导入成功");
      } else {
        throw new Error("格式错误");
      }
    } catch {
      ElMessage.error("词库导入失败");
    }
  };
  reader.readAsText(file.raw);
}

// AI生成词库相关
// 读取文件为base64
function readFileAsBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve((reader.result as string).split(",")[1]);
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
}
// AI生成词库
async function fetchWordLibraries(
  productName: string,
  imageFile?: File,
  aiType?: string,
  supplement?: string
) {
  let imageBase64 = "";
  if (imageFile) {
    imageBase64 = await readFileAsBase64(imageFile);
  }

  const res = await fetch("http://121.41.45.224:3100/generate-word-libraries", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      productName,
      image: imageBase64,
      aiType,
      supplement,
    }),
  });

  const { success, data: result } = await res.json();
  if (!success) {
    ElNotification.closeAll();
    ElMessage.error("生成失败");
  }
  ElNotification.closeAll();
  ElMessage.success("AI词库生成成功！");
  return result;
}

// 校验数据必填项
async function autoGenerateLibraries() {
  if (!productName.value) {
    ElMessage.warning("请输入产品名称");
    return;
  }

  aiWordLibLoading.value = true;
  ElNotification({
    title: "正在生成词库",
    message: "AI正在生成关键词词库，预计需要 10~30 秒，请稍候...",
    type: "success",
    duration: 0, // 永不自动关闭，直到成功或失败
  });

  try {
    const { data: libraries } = await fetchWordLibraries(
      productName.value,
      selectedImageFile.value || undefined,
      selectedAiType.value,
      productSupplement.value
    );
    console.log(libraries);

    const existingNames = wordLibraries.value.map((lib) => lib.name);
    const existingWordSet = new Set<string>();
    wordLibraries.value.forEach((lib) =>
      lib.words?.forEach((w: any) =>
        existingWordSet.add(`${w.zh}|${w.en}`.toLowerCase())
      )
    );

    let addedCount = 0;

    libraries.forEach((lib: any) => {
      const existingIndex = wordLibraries.value.findIndex(
        (item) => item.name === lib.name
      );

      const incomingWords = lib.words || [];

      if (existingIndex !== -1) {
        // 已存在同名词库，合并去重
        const existingWordSet = new Set(
          wordLibraries.value[existingIndex].words.map((w: any) =>
            `${w.zh}|${w.en}`.toLowerCase()
          )
        );

        const newWords = incomingWords.filter((w: any) => {
          const key = `${w.zh}|${w.en}`.toLowerCase();
          return !existingWordSet.has(key);
        });

        if (newWords.length > 0) {
          wordLibraries.value[existingIndex].words.push(...newWords);
          console.log(
            `[合并] ${lib.name} 添加了 ${newWords.length} 个新关键词`
          );
        } else {
          console.log(`[忽略] ${lib.name} 中无新增关键词`);
        }
      } else {
        // 不存在该名称，直接新增
        wordLibraries.value.push({
          id: idCounter.value++,
          name: lib.name,
          words: incomingWords,
        });
        console.log(`[新增] 添加新词库：${lib.name}`);
      }
    });

    if (addedCount === 0) {
      ElMessage.warning("没有新的词库被添加（可能与现有重复）");
    } else {
      ElMessage.success(`成功生成并添加 ${addedCount} 个新词库！`);
    }

    // 保存
    const project = projectList.value.find(
      (p) => p.folderName === selectedProject.value
    );
    if (project) {
      const content = JSON.stringify(wordLibraries.value, null, 2);
      await window.electronAPI.saveFileSilently(
        content,
        project.folderPath + "\\词库.json"
      );
    }

    autoGenerateDialogVisible.value = false;
    selectedImageFile.value = null;
    productSupplement.value = "";
    productName.value = "";
  } catch (err: any) {
    console.error("[AI生成词库失败]", err);
    ElMessage.error("生成失败：" + err.message);
  } finally {
    aiWordLibLoading.value = false;
  }
}

function generateTitles() {
  const pools: string[][] = [];

  for (const config of titleCombineConfig.value) {
    const lib = wordLibraries.value.find((l) => l.id === config.libId);
    if (!lib || !lib.words?.length) continue;

    const words = lib.words
      .map((w: any) => w[config.field]?.trim())
      .filter(Boolean);
    if (words.length === 0) continue;

    pools.push(words);
  }

  const totalPossible = pools.reduce((acc, arr) => acc * arr.length, 1);
  if (totalPossible < generateCount.value) {
    ElMessage.warning(
      `最多可生成 ${totalPossible} 条，当前设置为 ${generateCount.value} 条，请调整`
    );
    return;
  }

  const set = new Set<string>();
  const tryLimit = generateCount.value * 10;
  let tries = 0;

  while (set.size < generateCount.value && tries++ < tryLimit) {
    const picked = pools.map(
      (arr) => arr[Math.floor(Math.random() * arr.length)]
    );
    const unique = [...new Set(picked)];

    if (unique.length === picked.length) {
      const title = unique.join(keywordJoiner.value);
      set.add(title);
    }
  }

  if (set.size < generateCount.value) {
    ElMessage.warning(`仅成功生成 ${set.size} 条唯一标题（已排除重复词）`);
  } else {
    ElMessage.success("标题生成成功");
  }

  const category = categoryOptions.value[0] || "";
  const newTitles = Array.from(set).map((t) => ({
    id: idCounter.value++,
    title: t,
    category,
  }));
  newTitles.forEach((t, n) => {
    t.id = productTitles.value.length + n;
  });
  productTitles.value.push(...newTitles);
}

// 打开批量设置分类弹窗
function batchSetCategory() {
  if (selectedRows.value.length === 0) {
    ElMessage.warning("请先选择标题");
    return;
  }

  // 设置默认选中的分类（第一个有效分类或空）
  batchSelectedCategory.value =
    categoryOptions.value.length > 0 ? categoryOptions.value[0] : null;

  batchCategoryDialogVisible.value = true;
}
function selectAllTitles() {
  const isAllSelected = productTitles.value.every((row) =>
    allSelectedRows.value.includes(row.title)
  );

  if (isAllSelected) {
    // 取消全选
    allSelectedRows.value = [];
  } else {
    // 勾选全部
    allSelectedRows.value = productTitles.value.map((row) => row.title);
  }

  // 更新表格的选择状态
  nextTick(() => {
    productPagedTitles.value.forEach((row: any) => {
      titleTableRef.value!.toggleRowSelection(
        row,
        allSelectedRows.value.includes(row.title)
      );
    });
  });
}

// 分页变化或刷新时，恢复选中状态
watch(productPagedTitles, () => {
  if (!titleTableRef.value) return;
  nextTick(() => {
    productPagedTitles.value.forEach((row: any) => {
      titleTableRef.value!.toggleRowSelection(
        row,
        allSelectedRows.value.includes(row)
      );
    });
  });
});
// 确认批量设置分类
function confirmBatchCategory() {
  if (!batchSelectedCategory.value) {
    ElMessage.warning("请先选择要设置的分类");
    return;
  }

  selectedRows.value.forEach((row) => {
    // 存储完整的分类对象
    row.category = {
      id: batchSelectedCategory.value!.id,
      name: batchSelectedCategory.value!.name,
    };
  });

  ElMessage.success("分类设置成功");
  batchCategoryDialogVisible.value = false;
}

// 删除所选标题
function batchDeleteTitles() {
  if (!selectedRows.value.length && !allSelectedRows.value.length) {
    ElMessage.warning("请选择要删除的标题");
    return;
  }
  if (allSelectedRows.value.length > 0) {
    return ElMessageBox.confirm(
      `确定要删除所选 ${selectedRows.value.length} 个标题吗？`
    )
      .then((res) => {
        if (res == "confirm") {
          // 过滤掉被选中的标题
          productTitles.value = productTitles.value.filter(
            (t) => !allSelectedRows.value.includes(t.title)
          );
          // 清空已选中的记录
          allSelectedRows.value = [];
          return ElMessage.success("已删除所选标题");
        }
      })
      .catch(() => {
        return ElMessage({
          type: "info",
          message: "已取消删除",
        });
      });
  }
  if (selectedRows.value.length > 0) {
    return ElMessageBox.confirm(
      `确定要删除所选 ${selectedRows.value.length} 个标题吗？`
    )
      .then((res) => {
        if (res == "confirm") {
          // 过滤掉被选中的标题
          productTitles.value = productTitles.value.filter((titleRow) => {
            // 检查当前行是否不在选中行中
            return !selectedRows.value.some(
              (t: any) => titleRow.title === t.title
            );
          });

          // 清空已选中的记录
          selectedRows.value = [];
          return ElMessage.success("已删除所选标题");
        }
      })
      .catch(() => {
        return ElMessage({
          type: "info",
          message: "已取消删除",
        });
      });
  }
}

function editTitle(row: any) {
  ElMessageBox.prompt("修改标题", {
    inputValue: row.title,
    confirmButtonText: "确定",
    cancelButtonText: "取消",
  }).then(({ value }) => {
    row.title = value;
    ElMessage.success("修改成功");
  });
}

async function exportTitleData() {
  const project = projectList.value.find(
    (p) => p.folderName === selectedProject.value
  );
  if (!project) return;

  const rows = productTitles.value.map((item) => ({
    产品标题: item.title,
    分类id: item.category?.id || "",
  }));

  const worksheet = XLSX.utils.json_to_sheet(rows, {
    header: ["分类id", "产品标题"],
  });
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Sheet1");

  const wbout = XLSX.write(workbook, {
    bookType: "xlsx",
    type: "array",
  });

  await window.electronAPI.saveFile(wbout, "产品标题.xlsx", project.folderPath);

  ElMessage.success("标题数据已导出");
}

// 项目切换时加载 Excel 数据
async function handleProjectChange() {
  const project = projectList.value.find(
    (p) => p.folderName === selectedProject.value
  );
  if (!project) return;

  const titlePath = `${project.folderPath}\\产品标题.xlsx`;
  const categoryPath = `${project.folderPath}\\类目数据.xlsx`;
  const wordLibPath = `${project.folderPath}\\词库.json`;

  await window.electronAPI.readExcel(categoryPath).then((rows: any[]) => {
    const uniqueCategories = new Map();
    rows.forEach((r) => {
      const key = `${r.分类id}_${r.类目名称}`;
      if (!uniqueCategories.has(key)) {
        uniqueCategories.set(key, {
          id: r.分类id,
          name: r.类目名称,
        });
      }
    });
    categoryOptions.value = Array.from(uniqueCategories.values());
  });
  // 读取标题数据时保持分类信息
  await window.electronAPI.readExcel(titlePath).then((rows: any[]) => {
    productTitles.value = rows.map((r: any, id: number) => ({
      id,
      title: r.产品标题 || "",
      category: {
        id: r.分类id || "",
        name:
          categoryOptions.value.find((c) => c.id === (r.分类id || ""))?.name ||
          "",
      },
    }));
  });
  console.log(productTitles.value);

  // 初始化读取词库
  // 1. 检查词库文件是否存在
  const existWordLib = await window.electronAPI.checkFileExists(wordLibPath);
  if (existWordLib) {
    // 2. 如果存在，读取并解析为 JSON
    await window.electronAPI
      .readFile(wordLibPath)
      .then((buf: AllowSharedBufferSource | undefined) => {
        try {
          const json = JSON.parse(new TextDecoder().decode(buf));
          if (Array.isArray(json)) {
            wordLibraries.value = json.map((item) => ({
              ...item,
              id: idCounter.value++,
            }));
            console.log(wordLibraries.value);

            ElMessage.success("已加载项目词库");
          }
        } catch (err) {
          console.warn("词库文件读取失败或格式错误：", err);
        }
      })
      .catch(() => {
        console.info("未检测到词库文件");
      });
  }
}

// 初始化
onMounted(async () => {
  try {
    const data = await window.electronAPI.loadProjectList();
    projectList.value = JSON.parse(data);
    if (projectList.value.length > 0) {
      selectedProject.value = projectList.value[0].folderName;
      handleProjectChange();
    }
  } catch (e) {
    ElMessage.error("加载项目失败");
  }
});
</script>
